# -*- coding: utf-8 -*-
"""M11_RETO - Copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNn92LQAxmCeG5JLQ30vdTrpTh64Qp6T

**RETO MODULO 11**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

c2 = "C2.txt"

c2_df= pd.read_fwf(c2)

c2_df.shape

c2_df.head()

"""**PIPELINE**"""

import regex as re
def tokeniza(texto):
    patron= "[\w-]+\p{L}+[\w]"
    return re.findall(patron, texto)

import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
nltk.download("stopwords")
stopwords_mine = stopwords.words("english")
def remove_stopwords(vector_texto):
    return [ palabra for palabra in vector_texto if palabra not in stopwords_mine ]

def preprocesa(texto):
    fn = [str.lower, tokeniza, remove_stopwords ]
    str_texto = texto.strip()
    for funcion in fn:
        str_texto = funcion(str_texto)
    return str_texto

c2_df["tokens"] = c2_df.tweets.apply(preprocesa)

c2_df.head()

#Espacio para la gráfica
fig, ax = plt.subplots(figsize=(20,7))
#Datos para graficar
ax = c2_df.tweets.str.len().plot.hist(bins=50, alpha=0.5, color='blue')
#Linea vertical para ubicar la media
plt.axvline(x=c2_df.tweets.str.len().mean(), ymin=0 , ymax=1, color='purple')
#Anotaciones de media y máximo
text_mean = 'Media: %d' % c2_df.tweets.str.len().mean()
text_max = 'Máximo: %d' % c2_df.tweets.str.len().max()

#configuración de caja de texto y flechas.
bbox = dict(boxstyle='Round', color='green', alpha=0.2, linewidth=0.9)
arrowprops = dict(facecolor='red', arrowstyle='fancy', connectionstyle='angle3')

#anotaciones de valores media y máximo
plt.annotate(text=text_mean, xy=(c2_df.tweets.str.len().mean(), 200), xytext=(100, 100), arrowprops=arrowprops, bbox=bbox)
plt.annotate(text=text_max, xy=(c2_df.tweets.str.len().max(), 1), xytext=(c2_df.tweets.str.len().max(), 100), arrowprops=arrowprops, bbox=bbox)

#configuración de la gráfica
plt.title('Candidato 1: longitud de caracteres')
plt.xlabel('Longitud de caracteres, por oración')
plt.ylabel('Cantidad')
plt.show()

c2_df["len_tokens"] = c2_df.tokens.apply(len)

c2_df.head()

"""**Graficacion de frecuencias**"""

from wordcloud import WordCloud

import matplotlib.pyplot as plt
from PIL import Image
import numpy as np

def nube_palabras(corpus, stopwords, color):
    stopwords = set(stopwords)
    wordcloud = WordCloud(
        background_color=color,
        stopwords=stopwords,
        max_words=100,
        max_font_size=45,
        random_state=1)

    wordcloud=wordcloud.generate(str(corpus))

    fig = plt.figure(1, figsize=(15, 15))
    plt.imshow(wordcloud)
    plt.axis('off')
    plt.show()

corpus_wc = [palabra for vpalabras in c2_df.tokens for palabra in vpalabras]
print(corpus_wc)

texto_wc = " ".join(palabra for palabra in corpus_wc)
print(texto_wc)

nube_palabras(texto_wc, stopwords.words("spanish"), "black")

"""# **Counter**"""

from collections import Counter

counter = Counter()

c2_df["repeticiones"] = c2_df.tokens.apply(counter.update)

c2_df.head()

print(counter)

"""# **Pysentimiento**"""

!pip install pysentimiento

from pysentimiento import create_analyzer

sentiment_ = create_analyzer(task="sentiment", lang="en")

emotions_ = create_analyzer(task="emotion", lang="en")

prediccion = sentiment_.predict(c2_df.tweets[0])

prediccion

prediccion_emo = emotions_.predict(c2_df.tweets[0])

prediccion_emo

def sentimientos(texto):
   print(texto)
   return sentiment_.predict(texto).output

def emociones(texto):
   print(texto)
   return emotions_.predict(texto).output

c2_df["sentimientos"] = c2_df.tweets.apply(sentimientos)

c2_df["emociones"] = c2_df.tweets.apply(emociones)

c2_df.head()

c2_df.emociones.value_counts().plot(kind= "bar")

c2_df.sentimientos.value_counts().plot(kind= "bar")

"""Conclusiones :
* Se ve en la nube de palabras que las mas frecuentes son : epn, hoy, mexico, morena, corrupcion, petroleo, pueblo, comites, gente, mafia, pais, gente, mafia, mañana,
* Con respecto a las emociones Pysentymientos los clasifico como los frecuentes fueron OTHERS y despues JOY
* Con respecto a los sentimientos Pysentimientos los clasifico como los mas frecuentes NEU y POS
"""